apiVersion: v2
name: searxng
description: SearXNG Helm chart with optional built-in Valkey, Ingress, and Gateway API HTTPRoute support
type: application
version: 0.1.6
appVersion: "2026.4.24-a7ac696b4"
kubeVersion: ">=1.27.0-0"
home: https://docs.searxng.org/
sources:
  - https://github.com/searxng/searxng
  - https://docs.searxng.org/
keywords:
  - searxng
  - search
  - metasearch
  - privacy
  - valkey
annotations:
  artifacthub.io/alternativeName: searxng
  artifacthub.io/category: networking
  artifacthub.io/license: Apache-2.0
  artifacthub.io/signKey: |
    fingerprint: 7651717325AD3B7C454F3ACC171B13BE46EFF678
    url: https://techpipe.io/keys/helm-signing-public.asc
  artifacthub.io/images: |
    - name: searxng
      image: docker.io/searxng/searxng:2026.4.17-e8299a4c3
    - name: valkey
      image: docker.io/valkey/valkey:9.0.3-trixie
  artifacthub.io/links: |
    - name: source
      url: https://github.com/searxng/searxng
    - name: documentation
      url: https://docs.searxng.org/
    - name: support
      url: https://github.com/searxng/searxng/issues
  artifacthub.io/changes: |
    - kind: added
      description: Initial chart release with optional Valkey, Ingress, and Gateway API HTTPRoute support.
