{{- if and (not .Values.caCertificates.existingConfigMap) (not .Values.caCertificates.existingSecret) (gt (len .Values.caCertificates.files) 0) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "searxng.caConfigMapName" . }}
  labels:
    {{- include "searxng.labels" . | nindent 4 }}
data:
  {{- range $name, $content := .Values.caCertificates.files }}
  {{ $name }}: |
{{ $content | nindent 4 }}
  {{- end }}
{{- end }}
