{{- if .Values.gateway.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "searxng.fullname" . }}
  labels:
    {{- include "searxng.labels" . | nindent 4 }}
    {{- with .Values.gateway.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.gateway.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  parentRefs:
    {{- toYaml .Values.gateway.parentRefs | nindent 4 }}
  {{- with .Values.gateway.hostnames }}
  hostnames:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    - matches:
        {{- toYaml .Values.gateway.matches | nindent 8 }}
      {{- with .Values.gateway.filters }}
      filters:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      backendRefs:
        - name: {{ include "searxng.fullname" . }}
          port: {{ .Values.service.port }}
{{- end }}
