{{- if and .Values.valkey.enabled .Values.valkey.auth.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "searxng.valkey.authSecretName" . }}
  labels:
    {{- include "searxng.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: {{ include "searxng.valkeyPasswordValue" . | quote }}
{{- end }}
